objc: true
clean: true
sdk: iphonesimulator

theme: ../../Themes/apple

module: AppCenter
module_version: 1.9.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/AppCenter.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../AppCenter-SDK-Apple/iOS/AppCenter.framework/Headers/AppCenter.h
framework_root: ../../../AppCenter-SDK-Apple/iOS/

root_url: https://docs.microsoft.com/appcenter/sdk/ios
github_url: https://github.com/Microsoft/AppCenter-SDK-Apple
github_file_prefix: "https://github.com/Microsoft/AppCenter-SDK-Apple/"

skip_undocumented: true

output: Generated/
